# Generated by Django 5.2.8 on 2025-12-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_slug_remove_sweet_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sweet',
            new_name='Sweets',
        ),
    ]
