# Generated by Django 6.0 on 2026-01-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_sweet_sweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sweets',
            new_name='Sweet',
        ),
    ]
